server:
  port: 2001
spring:
  cloud:
    gateway:
      discovery:
        #自动发现eureka里面的所有服务
        locator:
          enabled: true
          lower-case-service-id: true
      #根据routes配置转发
      #注意这里面访问/baidu时，实际上访问的是https://www.baidu.com/baidu
      #需要使用filters: - StripPrefix=1来删除/baidu
      routes:
      - id: user-service
        uri: https://www.baidu.com
        predicates:
          - Path=/baidu
        filters:
          - StripPrefix=1
      - id: user-service2
        uri: lb://eureka-client-user-service
        predicates:
          - Path=/user-service/**
        filters:
          - StripPrefix=1
  application:
    name: cloud-gateway

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/,http://admin:123456@localhost:8762/eureka/
    fetch-registry: true
    register-with-eureka: true

